A bunch of wrapping up things
jemmaissroff/go-interpreter pull request #19
Opened 2020-12-16 19:37 UTC by Mr4k

2020-12-16 19:39 UTC, Mr4k commented
This is not a great pr and probably needs more testing but would be good to merge in I think

2020-12-16 20:04 UTC, jemmaissroff requested changes

2020-12-16 20:04 UTC, jemmaissroff commented on ast/ast.go
> +func (self Span) merge(other Span) Span {
I think idiomatic go would be `s` or `span` instead of `self`

2020-12-16 20:04 UTC, jemmaissroff commented on ast/ast.go
> +type OffsetNode struct {
Can we remove `OffsetNode`?

2020-12-16 20:04 UTC, jemmaissroff commented on evaluator/builtins.go
> +			// NOTE this function is legacy to support tests from the old version
Can we remove this comment?

2020-12-16 20:04 UTC, jemmaissroff commented on evaluator/builtins.go
> +		"dep_diagraph": {
Could we name this `dependency_graph`?

2020-12-16 20:04 UTC, jemmaissroff commented on evaluator/evaluator.go
> +	res.Offset.ASTCreator = &ast.StringLiteral{Value: "OFFSET"}
Do we need this?

2020-12-16 20:04 UTC, jemmaissroff commented on evaluator/evaluator_test.go
> +	l := lexer.New(input, "test_file.koko")
Thanks for catching all these ❤️

2020-12-16 20:04 UTC, jemmaissroff commented on object/graphviz_utils.go
> +			for dep := range collapseOffsetNodes(off) {
Can this be: `out = append(out, collapseOffsetNodes(off)...)`?

2020-12-16 20:04 UTC, jemmaissroff commented on object/graphviz_utils.go
> +		fmt.Printf("HEAD: %+v\n", head)
Can we remove the print?

2020-12-16 20:04 UTC, jemmaissroff commented on object/object.go
> +			for link := range head.GetDependencyLinks() {
`queue = append(queue, head.GetDependencyLinks()...)`?

2020-12-16 20:04 UTC, jemmaissroff commented on object/object.go
> +			for link := range head.GetDependencyLinks() {
Same as above

2020-12-17 23:59 UTC, Mr4k commented on ast/ast.go
> +func (self Span) merge(other Span) Span {
👍

2020-12-18 00:01 UTC, Mr4k commented on evaluator/builtins.go
> +			// NOTE this function is legacy to support tests from the old version
👍

2020-12-18 00:04 UTC, Mr4k commented on evaluator/evaluator.go
> +	res.Offset.ASTCreator = &ast.StringLiteral{Value: "OFFSET"}
noooo we don't

2020-12-18 00:04 UTC, Mr4k commented on evaluator/evaluator_test.go
> +	l := lexer.New(input, "test_file.koko")
💯

2020-12-18 00:05 UTC, Mr4k commented on object/graphviz_utils.go
> +			for dep := range collapseOffsetNodes(off) {
actually was wrong about this one. It can't b/c it's a dictionary

2020-12-18 00:06 UTC, Mr4k commented on object/graphviz_utils.go
> +		fmt.Printf("HEAD: %+v\n", head)
for sure

2020-12-18 00:06 UTC, Mr4k commented on object/object.go
> +			for link := range head.GetDependencyLinks() {
same problem re dictionary

2020-12-18 00:06 UTC, Mr4k commented on object/object.go
> +			for link := range head.GetDependencyLinks() {
same problem re dictionary

2020-12-18 00:11 UTC, Mr4k commented on evaluator/builtins.go
> +		"dep_diagraph": {
I'm gonna hold off here b/c it breaks my blog post (haha we already have tech debt)

2020-12-18 00:11 UTC, merged